version: '3.8'

services:
  backend:
    build:
      context: ./backendleave
      dockerfile: Dockerfile
    ports:
      - "8289:5002"
    volumes:
      - ./backendleave:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      DB_HOST: db  
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: leave-management
    # Make sure container restarts on failure
    restart: unless-stopped

  frontend:
    build:
      context: ./frontendleave
      dockerfile: Dockerfile
    ports:
      - "8288:80"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_HOST=127.0.0.1
      - WDS_SOCKET_PORT=8288
      - HOST=0.0.0.0
      - PORT=8288

  db:
    image: postgres:15
    ports:
      - "8290:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: leave-management
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:


